/*
  # Create Workers Table
  # إنشاء جدول العمال والرواتب
*/

create table if not exists public.workers (
  id bigint generated by default as identity primary key,
  name text not null,
  salary numeric default 0,
  job_title text,
  start_date timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.workers enable row level security;

-- Create Policy (Allow all access for public/anon users for this demo)
create policy "Enable all access for all users" on public.workers for all using (true) with check (true);
