create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.categories enable row level security;

create policy "Enable read access for all users" on public.categories for select using (true);
create policy "Enable insert access for all users" on public.categories for insert with check (true);
create policy "Enable update access for all users" on public.categories for update using (true);
create policy "Enable delete access for all users" on public.categories for delete using (true);
