/*
  # Comprehensive Updates
  1. Create Sales Table
  2. Create App Users Table (Custom Registration)
  3. Add New Bank
*/

-- 1. Sales Table
create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  product_name text not null,
  quantity integer not null,
  total_price numeric not null,
  sale_date timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. App Users Table (Custom Registration)
create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text not null,
  password text not null, -- Note: In production, hash this. Storing plain for this specific request context.
  security_question text not null,
  activation_code text not null, -- Stored as text string
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Add New Bank (Hidden from buttons, visible in dropdowns)
insert into public.treasury_balances (name, amount) 
values ('بنك النيل', 0)
on conflict (name) do nothing;

-- Enable RLS
alter table public.sales enable row level security;
alter table public.app_users enable row level security;

create policy "Enable all access for sales" on public.sales for all using (true) with check (true);
create policy "Enable all access for app_users" on public.app_users for all using (true) with check (true);
