/*
  # Fix Backups Table Type Mismatch
  # إصلاح تعارض أنواع البيانات في جدول النسخ الاحتياطي
  
  1. Drop existing backups table if it exists (to clean up bad state)
  2. Recreate backups table with user_id as BIGINT to match app_users.id
*/

-- Drop the table if it exists to ensure a clean slate
drop table if exists public.backups;

-- Recreate the table with the correct data types
create table public.backups (
  id bigint generated by default as identity primary key,
  user_id bigint references public.app_users(id) on delete cascade, -- Changed from UUID to BIGINT
  backup_data jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.backups enable row level security;

-- Create Policy to allow access
create policy "Enable all access for all users" on public.backups for all using (true) with check (true);
