/*
  # Fix Backups Table Type Mismatch
  # إصلاح خطأ نوع البيانات في جدول النسخ الاحتياطي
  
  ERROR 42804 Fix:
  - The previous attempt failed because 'user_id' was UUID while 'app_users.id' is BIGINT.
  - This script drops the failed table and recreates it with 'user_id' as BIGINT.
*/

-- 1. Drop the table if it exists (to ensure clean slate)
drop table if exists public.backups;

-- 2. Create the table with correct types
create table public.backups (
  id bigint generated by default as identity primary key,
  user_id bigint references public.app_users(id) on delete cascade, -- Fixed: Changed to BIGINT
  backup_data jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable Security
alter table public.backups enable row level security;

-- 4. Create Access Policy
create policy "Enable all access for all users" on public.backups for all using (true) with check (true);
