/*
  # Comprehensive Fix for User ID Columns
  # إصلاح شامل لأعمدة user_id في جميع الجداول
  
  1. Checks if user_id exists, adds it if missing.
  2. Converts it to bigint safely (handling old UUIDs by setting them to NULL if incompatible).
  3. Recreates the backups table.
*/

-- Function to safely add or fix user_id column for a given table
create or replace function public.fix_userid_column(tbl text)
returns void as $$
begin
    -- 1. Add column if it does not exist
    if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = tbl and column_name = 'user_id') then
        execute format('alter table public.%I add column user_id bigint references public.app_users(id)', tbl);
    else
        -- 2. If exists, try to convert to bigint. 
        -- If data is incompatible (like UUID), it will be set to NULL to avoid errors.
        begin
            execute format('alter table public.%I drop constraint if exists %I_user_id_fkey', tbl, tbl);
        exception when others then null; end;

        execute format('alter table public.%I alter column user_id type bigint using (case when user_id::text ~ ''^\d+$'' then user_id::text::bigint else null end)', tbl);
        
        -- Re-add foreign key if not exists
        begin
            execute format('alter table public.%I add constraint %I_user_id_fkey foreign key (user_id) references public.app_users(id)', tbl, tbl);
        exception when others then null; end;
    end if;
end;
$$ language plpgsql;

-- Apply to all relevant tables
select public.fix_userid_column('products');
select public.fix_userid_column('categories');
select public.fix_userid_column('sales');
select public.fix_userid_column('expenses');
select public.fix_userid_column('treasury_balances');
select public.fix_userid_column('workers');
select public.fix_userid_column('wholesalers');
select public.fix_userid_column('customers');
select public.fix_userid_column('purchases');

-- Recreate Backups Table (Clean Slate)
drop table if exists public.backups;
create table public.backups (
  id bigint generated by default as identity primary key,
  user_id bigint references public.app_users(id),
  backup_data jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Backups
alter table public.backups enable row level security;
create policy "Enable all access for all users" on public.backups for all using (true) with check (true);

-- Clean up helper function
drop function public.fix_userid_column(text);
