/*
  # Fix Backups Table - Final
  # إصلاح جدول النسخ الاحتياطي نهائياً
  1. Drop existing table to clear conflicts.
  2. Recreate with correct `user_id` type (bigint) to match `app_users`.
*/

DROP TABLE IF EXISTS public.backups;

CREATE TABLE public.backups (
  id bigint generated by default as identity primary key,
  user_id bigint REFERENCES public.app_users(id),
  backup_data jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Security
ALTER TABLE public.backups ENABLE ROW LEVEL SECURITY;

-- Policy
CREATE POLICY "Enable all access for all users" ON public.backups FOR ALL USING (true) WITH CHECK (true);
