/*
  # Comprehensive Schema Update for Multi-tenancy
  # تحديث شامل لقاعدة البيانات لدعم تعدد المستخدمين
  
  1. New Tables (إنشاء جداول جديدة):
     - customers (العملاء)
     - purchases (المشتريات)
  
  2. Schema Updates (تحديث الجداول الحالية):
     - Add user_id column to all tables to link data to specific users.
     - إضافة عمود user_id لجميع الجداول لربط البيانات بالمستخدمين.
*/

-- 1. Create Customers Table | إنشاء جدول العملاء
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  user_id bigint, -- Link to app_users
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Enable RLS
alter table public.customers enable row level security;
-- Policy
create policy "Enable all access for customers" on public.customers for all using (true) with check (true);


-- 2. Create Purchases Table | إنشاء جدول المشتريات
create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  product_name text,
  quantity numeric,
  cost_price numeric,
  total_cost numeric,
  payment_method text,
  date text,
  user_id bigint, -- Link to app_users
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Enable RLS
alter table public.purchases enable row level security;
-- Policy
create policy "Enable all access for purchases" on public.purchases for all using (true) with check (true);


-- 3. Add user_id to existing tables safely | إضافة معرف المستخدم للجداول الحالية
do $$
begin
  -- Categories | الأصناف
  if not exists (select 1 from information_schema.columns where table_name = 'categories' and column_name = 'user_id') then
    alter table public.categories add column user_id bigint;
  end if;

  -- Products | المنتجات
  if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'user_id') then
    alter table public.products add column user_id bigint;
  end if;

  -- Sales | المبيعات
  if not exists (select 1 from information_schema.columns where table_name = 'sales' and column_name = 'user_id') then
    alter table public.sales add column user_id bigint;
  end if;

  -- Expenses | المصروفات
  if not exists (select 1 from information_schema.columns where table_name = 'expenses' and column_name = 'user_id') then
    alter table public.expenses add column user_id bigint;
  end if;

  -- Treasury Balances | الخزينة
  if not exists (select 1 from information_schema.columns where table_name = 'treasury_balances' and column_name = 'user_id') then
    alter table public.treasury_balances add column user_id bigint;
  end if;

  -- Workers | العمال
  if not exists (select 1 from information_schema.columns where table_name = 'workers' and column_name = 'user_id') then
    alter table public.workers add column user_id bigint;
  end if;

  -- Wholesalers | تجار الجملة
  if not exists (select 1 from information_schema.columns where table_name = 'wholesalers' and column_name = 'user_id') then
    alter table public.wholesalers add column user_id bigint;
  end if;
end $$;
