/*
  # Fix Schema & Missing Tables
  # إصلاح المخطط والجداول المفقودة
  
  This script checks for the existence of all required tables.
  If a table does not exist, it creates it.
  It also ensures the 'user_id' column exists in all tables for data privacy.
*/

-- 1. Wholesalers (تجار الجملة) - Fixing the specific error 42P01
CREATE TABLE IF NOT EXISTS public.wholesalers (
    id bigint generated by default as identity primary key,
    name text not null,
    user_id text, -- Using text to be compatible with both UUID and BigInt IDs
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Customers (العملاء)
CREATE TABLE IF NOT EXISTS public.customers (
    id bigint generated by default as identity primary key,
    name text not null,
    user_id text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Purchases (المشتريات)
CREATE TABLE IF NOT EXISTS public.purchases (
    id bigint generated by default as identity primary key,
    product_name text,
    quantity numeric,
    cost_price numeric,
    total_cost numeric,
    payment_method text,
    date text,
    user_id text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Workers (العمال والرواتب)
CREATE TABLE IF NOT EXISTS public.workers (
    id bigint generated by default as identity primary key,
    name text not null,
    salary numeric default 0,
    job_title text,
    start_date timestamp with time zone,
    user_id text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Ensure user_id exists in existing tables (Safety Check)

-- Products
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'user_id') THEN
        ALTER TABLE public.products ADD COLUMN user_id text;
    END IF;
END $$;

-- Categories
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'categories' AND column_name = 'user_id') THEN
        ALTER TABLE public.categories ADD COLUMN user_id text;
    END IF;
END $$;

-- Sales
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'sales' AND column_name = 'user_id') THEN
        ALTER TABLE public.sales ADD COLUMN user_id text;
    END IF;
END $$;

-- Expenses
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'expenses' AND column_name = 'user_id') THEN
        ALTER TABLE public.expenses ADD COLUMN user_id text;
    END IF;
END $$;

-- Treasury Balances
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'treasury_balances' AND column_name = 'user_id') THEN
        ALTER TABLE public.treasury_balances ADD COLUMN user_id text;
    END IF;
END $$;

-- 6. Enable RLS on new tables (Security)
ALTER TABLE public.wholesalers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;

-- 7. Create Policies (Open access for demo, logic handled in app)
CREATE POLICY "Enable all access for wholesalers" ON public.wholesalers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for customers" ON public.customers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for purchases" ON public.purchases FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for workers" ON public.workers FOR ALL USING (true) WITH CHECK (true);
