-- 1. إنشاء جدول إعدادات النظام (لتخزين أسماء البنوك وغيرها)
CREATE TABLE IF NOT EXISTS system_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- 2. إدخال أسماء البنوك الافتراضية (إذا لم تكن موجودة)
INSERT INTO system_settings (key, value) VALUES
  ('bank_name_1', 'البنك 1'),
  ('bank_name_2', 'البنك 2')
ON CONFLICT (key) DO NOTHING;

-- 3. التأكد من وجود جدول الديون
CREATE TABLE IF NOT EXISTS debts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  due_date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id)
);

-- 4. تفعيل سياسات الأمان (RLS) لجدول الإعدادات (اختياري، يسمح للجميع بالقراءة حالياً)
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON system_settings FOR SELECT USING (true);
CREATE POLICY "Allow authenticated update" ON system_settings FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated insert" ON system_settings FOR INSERT WITH CHECK (auth.role() = 'authenticated');
