/*
  # Fix Missing Tables
  # إصلاح الجداول المفقودة
  
  1. Create 'sales' table for storing transaction history.
  2. Create 'app_users' table for custom registration.
  3. Enable RLS policies.
*/

-- 1. Create Sales Table | إنشاء جدول المبيعات
create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  product_name text not null,
  quantity integer not null,
  total_price numeric not null,
  invoice_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Sales
alter table public.sales enable row level security;
create policy "Enable all access for all users" on public.sales for all using (true) with check (true);


-- 2. Create App Users Table | إنشاء جدول المستخدمين
create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  security_question text,
  activation_code text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for App Users
alter table public.app_users enable row level security;
create policy "Enable all access for all users" on public.app_users for all using (true) with check (true);
